name: example-environment
channels:
  - conda-forge
dependencies:
  - python=3.9
  - numpy
  - harmonica
  - verde
  - ensaio
  - boule
  - simpeg
  - pyproj
  - psutil
  - toolz
  - matplotlib
  - dill
  - pandas
  - partd
  - bokeh
  - ipympl
  - cmcrameri
  - netCDF4